import type { Language } from './i18n';

type DetailMessages = {
  companyDetails: string; verifyLedger: string; noReviews: string;
  searchReviews: string; allPositions: string; allStatuses: string;
  currentEmployee: string; formerEmployee: string;
  latest: string; salary: string; rating: string;
  dossier: string; creditCode: string; region: string; legalRepresentative: string;
  registeredCapital: string; establishmentDate: string; companyType: string;
  registeredAddress: string; businessScope: string; officialWebsite: string;
  linksAndMedia: string; open: string; invalidUrl: string; notProvided: string;
};

export const companyDetailI18n: Record<Language, DetailMessages> = {
  zh: { companyDetails: '公司详情信息', verifyLedger: '验证账本', noReviews: '未找到符合条件的评价', searchReviews: '搜索企业评价', allPositions: '全部职位', allStatuses: '全部任职状态', currentEmployee: '在职员工', formerEmployee: '离职员工', latest: '最新', salary: '薪资', rating: '评分', dossier: '企业基本与工商补充信息档案', creditCode: '统一社会信用代码', region: '国家/地区与城市', legalRepresentative: '法定代表人', registeredCapital: '注册资金', establishmentDate: '成立 / 注册日期', companyType: '企业类型', registeredAddress: '注册 / 住所地址', businessScope: '经营范围', officialWebsite: '官方网站', linksAndMedia: '相关链接与媒体展示', open: '打开', invalidUrl: '链接无效', notProvided: '未填写' },
  'zh-tw': { companyDetails: '公司詳細資訊', verifyLedger: '驗證帳本', noReviews: '找不到符合條件的評價', searchReviews: '搜尋企業評價', allPositions: '全部職位', allStatuses: '全部任職狀態', currentEmployee: '在職員工', formerEmployee: '離職員工', latest: '最新', salary: '薪資', rating: '評分', dossier: '企業基本與工商補充資訊檔案', creditCode: '統一社會信用代碼', region: '國家／地區與城市', legalRepresentative: '法定代表人', registeredCapital: '註冊資本', establishmentDate: '成立／註冊日期', companyType: '企業類型', registeredAddress: '註冊／住所地址', businessScope: '營業範圍', officialWebsite: '官方網站', linksAndMedia: '相關連結與媒體', open: '開啟', invalidUrl: '連結無效', notProvided: '未填寫' },
  en: { companyDetails: 'Company Details', verifyLedger: 'Verify Ledger', noReviews: 'No Reviews Found', searchReviews: 'Search company reviews', allPositions: 'All positions', allStatuses: 'All employment statuses', currentEmployee: 'Current employee', formerEmployee: 'Former employee', latest: 'Latest', salary: 'Salary', rating: 'Rating', dossier: 'Company Dossier & Corporate Details', creditCode: 'Credit Code', region: 'Country / Region & City', legalRepresentative: 'Legal Representative', registeredCapital: 'Registered Capital', establishmentDate: 'Establishment Date', companyType: 'Company Type', registeredAddress: 'Registered Address', businessScope: 'Business Scope', officialWebsite: 'Official Website', linksAndMedia: 'Associated Links & Media', open: 'Open', invalidUrl: 'Invalid URL', notProvided: 'Not provided' },
  ja: { companyDetails: '企業詳細情報', verifyLedger: '台帳を検証', noReviews: '該当するレビューがありません', searchReviews: '企業レビューを検索', allPositions: 'すべての職種', allStatuses: 'すべての在籍状況', currentEmployee: '在職中', formerEmployee: '退職済み', latest: '最新', salary: '給与', rating: '評価', dossier: '企業基本・登記情報', creditCode: '企業信用コード', region: '国／地域・都市', legalRepresentative: '代表者', registeredCapital: '資本金', establishmentDate: '設立日', companyType: '企業形態', registeredAddress: '登記住所', businessScope: '事業内容', officialWebsite: '公式サイト', linksAndMedia: '関連リンクとメディア', open: '開く', invalidUrl: '無効なURL', notProvided: '未入力' },
  ar: { companyDetails: 'تفاصيل الشركة', verifyLedger: 'التحقق من السجل', noReviews: 'لم يتم العثور على تقييمات', searchReviews: 'البحث في تقييمات الشركة', allPositions: 'جميع الوظائف', allStatuses: 'جميع حالات العمل', currentEmployee: 'موظف حالي', formerEmployee: 'موظف سابق', latest: 'الأحدث', salary: 'الراتب', rating: 'التقييم', dossier: 'ملف الشركة والبيانات التجارية', creditCode: 'رمز الائتمان', region: 'الدولة / المنطقة والمدينة', legalRepresentative: 'الممثل القانوني', registeredCapital: 'رأس المال المسجل', establishmentDate: 'تاريخ التأسيس', companyType: 'نوع الشركة', registeredAddress: 'العنوان المسجل', businessScope: 'نطاق الأعمال', officialWebsite: 'الموقع الرسمي', linksAndMedia: 'الروابط والوسائط ذات الصلة', open: 'فتح', invalidUrl: 'رابط غير صالح', notProvided: 'غير متوفر' },
  hi: { companyDetails: 'कंपनी विवरण', verifyLedger: 'लेजर सत्यापित करें', noReviews: 'कोई समीक्षा नहीं मिली', searchReviews: 'कंपनी समीक्षाएँ खोजें', allPositions: 'सभी पद', allStatuses: 'सभी रोजगार स्थितियाँ', currentEmployee: 'वर्तमान कर्मचारी', formerEmployee: 'पूर्व कर्मचारी', latest: 'नवीनतम', salary: 'वेतन', rating: 'रेटिंग', dossier: 'कंपनी और व्यावसायिक विवरण', creditCode: 'क्रेडिट कोड', region: 'देश / क्षेत्र और शहर', legalRepresentative: 'कानूनी प्रतिनिधि', registeredCapital: 'पंजीकृत पूंजी', establishmentDate: 'स्थापना तिथि', companyType: 'कंपनी प्रकार', registeredAddress: 'पंजीकृत पता', businessScope: 'व्यवसाय का दायरा', officialWebsite: 'आधिकारिक वेबसाइट', linksAndMedia: 'संबंधित लिंक और मीडिया', open: 'खोलें', invalidUrl: 'अमान्य लिंक', notProvided: 'उपलब्ध नहीं' },
  tr: { companyDetails: 'Şirket Detayları', verifyLedger: 'Kaydı Doğrula', noReviews: 'Yorum Bulunamadı', searchReviews: 'Şirket yorumlarında ara', allPositions: 'Tüm pozisyonlar', allStatuses: 'Tüm çalışma durumları', currentEmployee: 'Mevcut çalışan', formerEmployee: 'Eski çalışan', latest: 'En yeni', salary: 'Maaş', rating: 'Puan', dossier: 'Şirket ve Ticari Bilgiler', creditCode: 'Kredi kodu', region: 'Ülke / Bölge ve Şehir', legalRepresentative: 'Yasal temsilci', registeredCapital: 'Kayıtlı sermaye', establishmentDate: 'Kuruluş tarihi', companyType: 'Şirket türü', registeredAddress: 'Kayıtlı adres', businessScope: 'Faaliyet alanı', officialWebsite: 'Resmî web sitesi', linksAndMedia: 'İlgili bağlantılar ve medya', open: 'Aç', invalidUrl: 'Geçersiz bağlantı', notProvided: 'Belirtilmemiş' },
  es: { companyDetails: 'Detalles de la empresa', verifyLedger: 'Verificar registro', noReviews: 'No se encontraron opiniones', searchReviews: 'Buscar opiniones de la empresa', allPositions: 'Todos los puestos', allStatuses: 'Todas las situaciones laborales', currentEmployee: 'Empleado actual', formerEmployee: 'Antiguo empleado', latest: 'Más recientes', salary: 'Salario', rating: 'Puntuación', dossier: 'Ficha empresarial y datos mercantiles', creditCode: 'Código de crédito', region: 'País / Región y ciudad', legalRepresentative: 'Representante legal', registeredCapital: 'Capital registrado', establishmentDate: 'Fecha de constitución', companyType: 'Tipo de empresa', registeredAddress: 'Domicilio registrado', businessScope: 'Actividad empresarial', officialWebsite: 'Sitio web oficial', linksAndMedia: 'Enlaces y medios relacionados', open: 'Abrir', invalidUrl: 'Enlace no válido', notProvided: 'No disponible' },
  bo: { companyDetails: 'ཚོང་ལས་ཞིབ་ཕྲ།', verifyLedger: 'ཐོ་དེབ་ར་སྤྲོད།', noReviews: 'དཔྱད་བརྗོད་མ་རྙེད།', searchReviews: 'ཚོང་ལས་དཔྱད་བརྗོད་འཚོལ།', allPositions: 'ལས་གནས་ཚང་མ།', allStatuses: 'ལས་ཀའི་གནས་སྟངས་ཚང་མ།', currentEmployee: 'ད་ལྟའི་ལས་མི།', formerEmployee: 'སྔོན་གྱི་ལས་མི།', latest: 'གསར་ཤོས།', salary: 'གླ་ཕོགས།', rating: 'སྐར་གྲངས།', dossier: 'ཚོང་ལས་དང་ཐོ་འགོད་ཆ་འཕྲིན།', creditCode: 'ཡིད་རྟོན་ཨང་།', region: 'རྒྱལ་ཁབ / ས་ཁུལ་དང་གྲོང་ཁྱེར།', legalRepresentative: 'ཁྲིམས་མཐུན་འཐུས་མི།', registeredCapital: 'ཐོ་འགོད་མ་རྩ།', establishmentDate: 'གསར་འཛུགས་ཚེས་གྲངས།', companyType: 'ཚོང་ལས་རིགས།', registeredAddress: 'ཐོ་འགོད་ཁ་བྱང་།', businessScope: 'ལས་སྒོའི་ཁྱབ་ཁོངས།', officialWebsite: 'གཞུང་འབྲེལ་དྲ་ཚིགས།', linksAndMedia: 'འབྲེལ་ཡོད་དྲ་ཐག་དང་བརྡ་ལམ།', open: 'ཁ་ཕྱེ།', invalidUrl: 'དྲ་ཐག་ནོར་འཁྲུལ།', notProvided: 'མ་བཀོད།' },
};

export const companyAiReportI18n: Record<Language, {
  relatedTitle: string; relatedDesc: string; reviewUnit: string;
  sameNameRegion: string; similarName: string; scope: string;
}> = {
  zh: { relatedTitle: '选择要合并分析的分区或相似企业', relatedDesc: '只有勾选的企业评价会加入本次报告，原始企业统计不会改变。', reviewUnit: '条评价', sameNameRegion: '同名分区', similarName: '名称相似', scope: '分析范围：' },
  'zh-tw': { relatedTitle: '選擇要合併分析的分區或相似企業', relatedDesc: '只有勾選的企業評價會加入本次報告，原始企業統計不會改變。', reviewUnit: '筆評價', sameNameRegion: '同名分區', similarName: '名稱相似', scope: '分析範圍：' },
  en: { relatedTitle: 'Include regional or similar companies', relatedDesc: 'Only selected company reviews are included; source statistics remain unchanged.', reviewUnit: 'reviews', sameNameRegion: 'Same-name region', similarName: 'Similar name', scope: 'Scope:' },
  ja: { relatedTitle: '地域別・類似企業を分析に含める', relatedDesc: '選択した企業のレビューのみが追加され、元の統計は変更されません。', reviewUnit: '件のレビュー', sameNameRegion: '同名の地域企業', similarName: '類似名称', scope: '分析範囲：' },
  ar: { relatedTitle: 'تضمين الشركات الإقليمية أو المشابهة', relatedDesc: 'تُضاف تقييمات الشركات المحددة فقط، ولا تتغير الإحصاءات الأصلية.', reviewUnit: 'تقييمات', sameNameRegion: 'منطقة بالاسم نفسه', similarName: 'اسم مشابه', scope: 'نطاق التحليل:' },
  hi: { relatedTitle: 'क्षेत्रीय या समान कंपनियाँ शामिल करें', relatedDesc: 'केवल चुनी गई कंपनियों की समीक्षाएँ जुड़ेंगी; मूल आँकड़े नहीं बदलेंगे।', reviewUnit: 'समीक्षाएँ', sameNameRegion: 'समान नाम वाला क्षेत्र', similarName: 'समान नाम', scope: 'विश्लेषण का दायरा:' },
  tr: { relatedTitle: 'Bölgesel veya benzer şirketleri dahil et', relatedDesc: 'Yalnızca seçilen şirket yorumları eklenir; kaynak istatistikler değişmez.', reviewUnit: 'yorum', sameNameRegion: 'Aynı adlı bölge', similarName: 'Benzer ad', scope: 'Analiz kapsamı:' },
  es: { relatedTitle: 'Incluir empresas regionales o similares', relatedDesc: 'Solo se incluyen las opiniones seleccionadas; las estadísticas originales no cambian.', reviewUnit: 'opiniones', sameNameRegion: 'Región con el mismo nombre', similarName: 'Nombre similar', scope: 'Ámbito del análisis:' },
  bo: { relatedTitle: 'ས་ཁུལ་ལམ་འདྲ་མཚུངས་ཚོང་ལས་དཔྱད་ཞིབ་ནང་འཇུག', relatedDesc: 'འདེམས་པའི་ཚོང་ལས་དཔྱད་བརྗོད་ཁོ་ན་སྙན་ཞུར་འཇུག', reviewUnit: 'དཔྱད་བརྗོད།', sameNameRegion: 'མིང་གཅིག་ས་ཁུལ།', similarName: 'མིང་འདྲ་མཚུངས།', scope: 'དཔྱད་ཞིབ་ཁྱབ་ཁོངས།' },
};

export const companyPageCommonI18n: Record<Language, {
  notFound: string; notFoundDesc: string; ledgerEntries: string;
  maintainProfile: string; maintainProfileDesc: string; auditing: string;
}> = {
  zh: { notFound: '未找到该企业', notFoundDesc: '该企业可能尚未创建评价，或者标识符无效。', ledgerEntries: '笔存证记录', maintainProfile: '社区维护企业档案', maintainProfileDesc: '补充缺失信息，或提交对现有企业资料的修改建议。', auditing: '审计中…' },
  'zh-tw': { notFound: '找不到該企業', notFoundDesc: '該企業可能尚未建立評價，或識別碼無效。', ledgerEntries: '筆存證記錄', maintainProfile: '社群維護企業檔案', maintainProfileDesc: '補充缺失資訊，或提出企業資料修改建議。', auditing: '稽核中…' },
  en: { notFound: 'Company Not Found', notFoundDesc: 'This company may not have reviews yet, or the identifier is invalid.', ledgerEntries: 'verified entries', maintainProfile: 'Maintain this company profile', maintainProfileDesc: 'Add missing information or propose changes to existing company details.', auditing: 'Auditing…' },
  ja: { notFound: '企業が見つかりません', notFoundDesc: 'レビューが未登録か、識別子が無効です。', ledgerEntries: '件の検証済み記録', maintainProfile: '企業情報を共同管理', maintainProfileDesc: '不足情報の追加や既存情報の変更を提案できます。', auditing: '監査中…' },
  ar: { notFound: 'لم يتم العثور على الشركة', notFoundDesc: 'قد لا توجد تقييمات لهذه الشركة بعد، أو أن المعرّف غير صالح.', ledgerEntries: 'سجلات موثقة', maintainProfile: 'المساهمة في ملف الشركة', maintainProfileDesc: 'أضف المعلومات الناقصة أو اقترح تعديلات على البيانات الحالية.', auditing: 'جارٍ التدقيق…' },
  hi: { notFound: 'कंपनी नहीं मिली', notFoundDesc: 'इस कंपनी की समीक्षा अभी नहीं है या पहचानकर्ता अमान्य है।', ledgerEntries: 'सत्यापित प्रविष्टियाँ', maintainProfile: 'कंपनी प्रोफ़ाइल बनाए रखें', maintainProfileDesc: 'गुम जानकारी जोड़ें या मौजूदा विवरण में बदलाव सुझाएँ।', auditing: 'ऑडिट जारी है…' },
  tr: { notFound: 'Şirket Bulunamadı', notFoundDesc: 'Bu şirket için henüz yorum olmayabilir veya tanımlayıcı geçersizdir.', ledgerEntries: 'doğrulanmış kayıt', maintainProfile: 'Şirket profilini güncelle', maintainProfileDesc: 'Eksik bilgileri ekleyin veya mevcut bilgiler için değişiklik önerin.', auditing: 'Denetleniyor…' },
  es: { notFound: 'Empresa no encontrada', notFoundDesc: 'Puede que esta empresa aún no tenga opiniones o que el identificador no sea válido.', ledgerEntries: 'registros verificados', maintainProfile: 'Mantener el perfil de la empresa', maintainProfileDesc: 'Añade información pendiente o propón cambios en los datos existentes.', auditing: 'Auditando…' },
  bo: { notFound: 'ཚོང་ལས་མ་རྙེད།', notFoundDesc: 'ཚོང་ལས་འདིར་དཔྱད་བརྗོད་མེད་པའམ་ངོས་འཛིན་ནོར་ཡོད།', ledgerEntries: 'ར་སྤྲོད་ཐོ་འགོད།', maintainProfile: 'ཚོང་ལས་ཆ་འཕྲིན་མཉམ་སྐྱོང་།', maintainProfileDesc: 'ཆ་འཕྲིན་ཆད་པ་ཁ་སྐོང་ངམ་བཟོ་བཅོས་གྲོས་འཆར་འབུལ།', auditing: 'ཞིབ་བཤེར་བྱེད་བཞིན་པ…' },
};
